### PR TITLE
Sketch mobile ui

### PR DESCRIPTION
**Pull request by michaelsanford**

### CODE REVIEW

**Comment by michaelsanford** [comment]
Got a little trigger-happy there…

**Comment by PaulKinlan** [comment]
Damn, I can't pull it in (it was closed) - can you resend a new one :\

**Comment by PaulKinlan** [comment]
Or un-close it.

**Comment by PaulKinlan** [comment]
Ha, open is the word I meant.

**Comment by PaulKinlan** [comment]
nevermind, I found your code and pulled it in. :)

**Comment by michaelsanford** [comment]
Hey Paul,

That's why I closed it. I hadn't meant to send it yet, having mangled my
branch a tad. I'll take a look in about 2 hours and see what happened.

Feel free to revert it now if it looks off.

Sorry about that!

**Pull request closed without merging**
